dbt_train:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: hattie.db.elephantsql.com
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: zxyurssx
      schema: src

  target: dev
