dbt_train:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: 172.20.0.1
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: dbt_test
      schema: src

  target: dev
